-- MySQL Script generated by MySQL Workbench
-- Wed Nov 30 12:15:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

drop database if exists YourPath;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `YourPath` DEFAULT CHARACTER SET utf8 ;
USE `YourPath` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YourPath`.`User` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `psswrd` VARCHAR(45) NOT NULL,
  `tel` INT(9) NULL,
  `ubicacion` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  `descripcion` VARCHAR(200) NULL,
  `link` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Punto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YourPath`.`Punto` (
  `punto_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `organización` VARCHAR(45) NOT NULL,
  `init_date` DATE NULL,
  `end_date` DATE NULL,
  `descripcion` VARCHAR(200) NULL,
  `state` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`punto_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
